export const projects = [
  {
  id: "hmifunsri-2025",
  title: "HMIF UNSRI 2025",
  description: "An official web platform for HMIF UNSRI 2025 that serves as a profile and information hub for the organization. It features an interactive landing page, organizational structure, work programs, academic opportunities, and a public aspiration submission system. Admin functionalities are secured and managed using Firebase.",
  image: "/portofolio-image/hmifunsri-2025.jpg?height=600&width=1200",
  technologies: ["Next.js", "Firebase", "Tailwind CSS", "Nodemailer"],
  features: [
    "Interactive landing page introducing HMIF UNSRI 2025",
    "About Us section highlighting vision, mission, and structure",
    "Member profile page showcasing BPH, departments, and divisions",
    "Work Program page detailing activities of each department and division",
    "Academic page listing competitions, scholarships, and seminars/webinars",
    "Aspiration page allowing users to submit feedback to HMIF",
    "Admin-only dashboard with Firebase authentication",
    "Department management system (admin-only)",
    "Division management system (admin-only)",
    "Program/work agenda management (admin-only)",
    "Competition management (admin-only)",
    "Scholarship management (admin-only)",
    "Seminar/webinar management (admin-only)",
    "Member management (admin-only)",
    "Subscription management with mass email delivery via Nodemailer (admin-only)",
    "Fully integrated content management using Firebase"
  ],
  category: "Full Stack Development",
  year: "2025",
  links: {
    live: "https://www.hmifunsri.com/",
    github: "https://github.com/HMIF-UNSRI"
  }
},
  {
    id: "jurisconsult",
    title: "JurisConsult",
    description: "An AI-powered legal consultation platform that provides instant, accurate, and private answers to legal questions based on Indonesian law, accessible 24/7.",
    image: "/portofolio-image/jurisconsult.jpg?height=600&width=1200",
    technologies: ["Next.js", "Firebase", "Tailwind CSS", "Gemini API"],
    features: [
      "Modern landing page with smooth UI and dark mode support",
      "AI-powered legal assistant for instant responses",
      "Section-based chat interface similar to GPT",
      "24/7 legal consultation with no time or location limits",
      "End-to-end encrypted chat for privacy protection",
      "Accurate legal information from updated Indonesian law database",
    ],
    category: "Full Stack Development",
    year: "2025",
    links: {
      live: "https://juris-consult.vercel.app/",
      github: "#",
    },
  },
  {
    id: "LegalAssist",
    title: "LegalAssist",
    description: "A modern legal platform that enhances access to legal assistance in Indonesia with AI-powered insights, expert consultations, and a collaborative community forum.",
    image: "/portofolio-image/legalassist.jpg?height=600&width=1200",
    technologies: ["Next.js", "Firebase", "Gemini API", "Tailwind CSS", "Web Socket"],
    features: [
      "AI-powered legal assistant integrated with Gemini API",
      "Real-time chat with verified legal experts",
      "Community-driven legal forum for discussions",
      "Secure sign-in and sign-up authentication",
      "Admin dashboard for user and role management",
    ],
    category: "Full Stack Development",
    year: "2025",
    links: {
      live: "https://law-consultation-indonesia.vercel.app/",
      github: "#",
    },
  },
  {
    id: "srifoton-2024",
    title: "SRIFOTON 2024",
    description: "A comprehensive event management platform for SRIFOTON 2024, featuring event information and a registration system for various competitions including Web Development, UI/UX Design, and Competitive Programming.",
    image: "/portofolio-image/srifoton.png?height=600&width=1200",
    technologies: ["Next.js", "Firebase", "Tailwind CSS", "React", "TypeScript"],
    features: ["Event information and details", "Competition registration system", "User authentication and profiles", "Admin dashboard for event management", "Real-time updates and notifications"],
    category: "Full Stack Development",
    year: "2024",
    links: {
      live: "https://www.instagram.com/srifoton.official/",
      github: "#",
    },
  },
  {
    id: "grahaya-karya",
    title: "Manajemen Grahaya Karya Muara Bulian",
    description: "A full-stack landing page for the Management Department at Universitas Grahaya Karya Muara Bulian. The website showcases the department's programs, faculty, and resources for prospective and current students.",
    image: "/portofolio-image/ugkmb.jpg?height=600&width=1200",
    technologies: ["Next.js", "Node.js", "Express", "MongoDB", "Tailwind CSS"],
    features: ["Department informations", "Faculty profiles and expertise", "News and events calendar"],
    category: "Full Stack Development",
    year: "2024",
    links: {
      live: "https://manajamen-ugkmb.vercel.app/",
      github: "#",
    },
  },
];
